import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";

import { useEffect } from "react";
import jwt_decode from "jwt-decode";

import SideBar from "../components/SideBar";
import HomeComp from "../components/HomeComp";

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    try {
      const token = localStorage.getItem("token");
      const user = jwt_decode(token);
      if (!user) {
        localStorage.removeItem("token");
      }
    } catch (err) {
      router.push("/login");
    }
  }, []);
  const [sideBarOpen, setSideBarOpen] = useState(true);
  return (
    <>
      <Head>
        <title>OSWAL BHAVAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <div className="flex"  
      style={{ backgroundImage: 'url("./bg.jpg")', 
      backgroundSize: "cover",
      backgroundPosition: "center",
      width: "100%",
      height: "100%", }}>
        <SideBar setSideBarOpen={setSideBarOpen} />
        <div
          className={`h-screen p-7 ${
            sideBarOpen ? "w-[85%] ml-64 sm:ml-72" : "w-[95.85%] ml-20"
          } duration-300`}
        >
          <HomeComp />
        </div>
      </div>
    </>
  );
}
