import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

import { loginAdmin } from "../utils/api";

import Login from "../components/Login";

export default function LoginPage() {
  const router = useRouter();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [message, setMessage] = useState("");
  const [success, setSuccess] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();

    setEmail("");
    setPassword("");

    const adminData = { email, password };

    try {
      const config = {
        headers: {
          "Content-Type": "application/json",
        },
      };
      const data = JSON.stringify(adminData);

      const result = await loginAdmin(data, config);

      setMessage(result.message);

      if (result.user) {
        setSuccess(true);
        localStorage.setItem("token", result.user);
        router.push("/");
      }

      setTimeout(() => {
        setMessage("");
        setSuccess(false);
      }, 3000);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>

      <div>
        <Login
          handleSubmit={handleSubmit}
          message={message}
          success={success}
          email={email}
          setEmail={setEmail}
          password={password}
          setPassword={setPassword}
        />
      </div>
    </>
  );
}
