import Head from "next/head";

import { useState } from "react";

import Register from "../components/Register";
import { registerAdmin } from "../utils/api";

export default function RegistrationPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [bgCol, setBgCol] = useState("red-100");
  const [textCol, setTextCol] = useState("red-900");

  const handleSubmit = async (e) => {
    e.preventDefault();

    setEmail("");
    setPassword("");

    const newAdmin = { email, password };

    try {
      const config = {
        headers: {
          "Content-Type": "application/json",
        },
      };
      const data = JSON.stringify(newAdmin);

      const result = await registerAdmin(data, config);
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center flex-col h-screen">
        <Register
          handleSubmit={handleSubmit}
          message={message}
          bgCol={bgCol}
          textCol={textCol}
          email={email}
          setEmail={setEmail}
          password={password}
          setPassword={setPassword}
        />
      </div>
    </>
  );
}
